LOAD DATA
CHARACTERSET WE8ISO8859P1
INFILE '/home/aylin/workspaceNeon/ProyectoArchivos/Usuarios.txt"' 
INTO TABLE USUARIO_TEMP TRUNCATE
FIELDS (
	ID POSITION(1:5) "TRIM(:ID)",
	GRUPO POSITION(6:25) "TRIM(:GRUPO)",
	NOMBRE POSITION(26:45) "TRIM(:NOMBRE)",
	CLAVE POSITION(46:65) "TRIM(:CLAVE)"	
)

