LOAD DATA
CHARACTERSET WE8ISO8859P1
INFILE '/home/aylin/workspaceNeon/ProyectoArchivos/Permisos.txt"' 
INTO TABLE PERMISO_TEMP TRUNCATE
FIELDS (
	GRUPO POSITION(6:25) "TRIM(:GRUPO)",
	NOMBRE POSITION(26:45) "TRIM(:NOMBRE)",
	CLAVE POSITION(46:65) "TRIM(:CLAVE)"	
)

